import type { Metadata } from "next";
import "./globals.css";
import Navbar from '../components/landingpage/navbar'
import WhatsAppButton from "@/components/common/WhatsAppButton";
import Footer from '@/components/landingpage/Footer'

export const metadata: Metadata = {
  title: "Pride Walls",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="antialiased">
        <Navbar />
        {children}
        <WhatsAppButton />
        <Footer />
      </body>
    </html>
  );
}
